name: newman tests
on:
  pull_request:
    branches: [master]

concurrency:
  group: newman-tests-${{github.event.pull_request.number}}
  cancel-in-progress: true

jobs:
  newman-global:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: newman
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: npm i newman-reporter-testomatio newman -g
      - run: TESTOMATIO=m6ef70356h7c newman run collection.json -e env.json -r testomatio

  newman-local:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: newman
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: npm i
      - run: TESTOMATIO=m6ef70356h7c npm run test
